import { Section } from "../types";

export let originalItems = [
  { id: "100", name: "Hildegaard", status: "status3" },
  { id: "101", name: "Jorry", status: "status1" },
  { id: "102", name: "Celestyna", status: "status1" },
  { id: "103", name: "Phylis", status: "status3" },
  { id: "104", name: "Lorne", status: "status1" },
  { id: "105", name: "Phedra", status: "status3" },
  { id: "106", name: "Dede", status: "status3" },
  { id: "107", name: "Konstance", status: "status3" },
  { id: "108", name: "Calla", status: "status3" },
  { id: "109", name: "Flory", status: "status1" },
  { id: "110", name: "Esmeralda", status: "status1" },
  { id: "111", name: "Sissy", status: "status2" },
  { id: "112", name: "Tybie", status: "status3" },
  { id: "113", name: "Dolli", status: "status2" },
  { id: "114", name: "Ingrid", status: "status1" },
  { id: "115", name: "Marline", status: "status2" },
  { id: "116", name: "Beth", status: "status3" },
  { id: "117", name: "Babita", status: "status1" },
  { id: "118", name: "Nannie", status: "status2" },
  { id: "119", name: "Dione", status: "status1" },
  { id: "120", name: "Nicoli", status: "status2" },
  { id: "121", name: "Dianemarie", status: "status1" },
  { id: "122", name: "Vanessa", status: "status2" },
  { id: "123", name: "Fawne", status: "status1" },
  { id: "124", name: "Johna", status: "status3" },
  // { id: "125", name: "Kellen", status: 'status1' },
  // { id: "126", name: "Janeczka", status: 'status2' },
  // { id: "127", name: "Sindee", status: 'status2' },
  // { id: "128", name: "Annice", status: 'status2' },
  // { id: "129", name: "Wileen", status: 'status1' },
  // { id: "130", name: "Sonni", status: 'status2' },
  // { id: "131", name: "Olwen", status: 'status2' },
  // { id: "132", name: "Emmey", status: 'status3' },
  // { id: "133", name: "Philis", status: 'status1' },
  // { id: "134", name: "Morganica", status: 'status1' },
  // { id: "135", name: "Karolina", status: 'status1' },
  // { id: "136", name: "Lynea", status: 'status1' },
  // { id: "137", name: "Margalo", status: 'status1' },
  // { id: "138", name: "Zia", status: 'status1' },
  // { id: "139", name: "Ginnie", status: 'status3' },
  // { id: "140", name: "Lynnea", status: 'status1' },
  // { id: "141", name: "Lilith", status: 'status2' },
  // { id: "142", name: "Amara", status: 'status2' },
  // { id: "143", name: "Kristan", status: 'status1' },
  // { id: "144", name: "Danny", status: 'status2' },
  // { id: "145", name: "Molli", status: 'status3' },
  // { id: "146", name: "Amalie", status: 'status3' },
  // { id: "147", name: "Raf", status: 'status1' },
  // { id: "148", name: "Henriette", status: 'status2' },
  // { id: "149", name: "Elyssa", status: 'status1' },
  // { id: "150", name: "Merci", status: 'status3' },
];

export let originalItemsOrdered: Section = {
  status1: [
    { id: "101", name: "Jorry", status: "status1" },
    { id: "102", name: "Celestyna", status: "status1" },
    { id: "104", name: "Lorne", status: "status1" },
    { id: "109", name: "Flory", status: "status1" },
    { id: "110", name: "Esmeralda", status: "status1" },
    { id: "114", name: "Ingrid", status: "status1" },
    { id: "117", name: "Babita", status: "status1" },
    { id: "119", name: "Dione", status: "status1" },
    { id: "121", name: "Dianemarie", status: "status1" },
    { id: "123", name: "Fawne", status: "status1" },
  ],
  status2: [
    // { id: "111", name: "Sissy", status: "status2" },
    // { id: "113", name: "Dolli", status: "status2" },
    // { id: "115", name: "Marline", status: "status2" },
    // { id: "118", name: "Nannie", status: "status2" },
    // { id: "120", name: "Nicoli", status: "status2" },
    // { id: "122", name: "Vanessa", status: "status2" },
  ],
  status3: [
    { id: "100", name: "Hildegaard", status: "status3" },
    { id: "103", name: "Phylis", status: "status3" },
    { id: "105", name: "Phedra", status: "status3" },
    { id: "106", name: "Dede", status: "status3" },
    { id: "107", name: "Konstance", status: "status3" },
    { id: "108", name: "Calla", status: "status3" },
    { id: "112", name: "Tybie", status: "status3" },
    { id: "116", name: "Beth", status: "status3" },
    { id: "124", name: "Johna", status: "status3" },
  ],
};
